/**
 * Auto-generated API implementations
 * This file is automatically generated based on your API dependencies.
 * Do not edit manually - changes will be overwritten.
 */

import { Agent } from '@greaseclaw/workflow-sdk';

/**
 * Task status type
 */
export type TaskStatus = 'waiting' | 'running' | 'succeeded' | 'failed';

/**
 * Execution result returned by all API calls
 */
export interface ExecutionResult {
  success: boolean;
  error?: string;
  task?: {
    id: string;
    status: TaskStatus;
    extract_data?: string;
    metrics_tokens: number;
    metrics_time: number;
  };
}

/**
 * WorkflowApis interface - methods generated from your API dependencies
 */
export interface WorkflowApis {
  export_goods: (start_time: string, end_time: string) => Promise<ExecutionResult>;
  get_goods_report: () => Promise<ExecutionResult>;
  export_stock: () => Promise<ExecutionResult>;
  get_stock_report: () => Promise<ExecutionResult>;
  export_sales: (start_time?: string, end_time?: string) => Promise<ExecutionResult>;
  get_sales_report: () => Promise<ExecutionResult>;
}


/**
 * Creates API client using agent.call()
 */
export function createWorkflowApis(agent: Agent): WorkflowApis {
  return {
  /**
   * Export goods
   * 导出商品数据
   * @endpoint /v1/custom/https-store-youzan-com-export-goods-gf9oj9
   */
  async export_goods(start_time: string, end_time: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/https-store-youzan-com-export-goods-gf9oj9', {
      method: 'POST',
      body: { start_time, end_time },
    });
    return data;
  },

  /**
   * Get goods report
   * 获取导出商品数据
   * @endpoint /v1/custom/https-store-youzan-com-get-goods-report-38unjm
   */
  async get_goods_report(): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/https-store-youzan-com-get-goods-report-38unjm', {
      method: 'POST',
    });
    return data;
  },

  /**
   * Export stock
   * 导出库存数据
   * @endpoint /v1/custom/https-store-youzan-com-export-stock-k7is4d
   */
  async export_stock(): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/https-store-youzan-com-export-stock-k7is4d', {
      method: 'POST',
    });
    return data;
  },

  /**
   * Get stock report
   * 获取导出库存数据
   * @endpoint /v1/custom/store-youzan-com-get-stock-report-lc82o7
   */
  async get_stock_report(): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/store-youzan-com-get-stock-report-lc82o7', {
      method: 'POST',
    });
    return data;
  },

  /**
   * Export sales
   * 导出销售数据
   * @endpoint /v1/custom/store-youzan-com-export-sales-i69zt7
   */
  async export_sales(start_time?: string, end_time?: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/store-youzan-com-export-sales-i69zt7', {
      method: 'POST',
      body: { start_time, end_time },
    });
    return data;
  },

  /**
   * Get sales report
   * 获取导出销售数据
   * @endpoint /v1/custom/store-youzan-com-get-sales-report-wzznwo
   */
  async get_sales_report(): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/store-youzan-com-get-sales-report-wzznwo', {
      method: 'POST',
    });
    return data;
  },
  };
}
