/**
 * Auto-generated API implementations
 * This file is automatically generated based on your API dependencies.
 * Do not edit manually - changes will be overwritten.
 */

import { Agent } from '@greaseclaw/workflow-sdk';

/**
 * Task status type
 */
export type TaskStatus = 'waiting' | 'running' | 'succeeded' | 'failed';

/**
 * Execution result returned by all API calls
 */
export interface ExecutionResult {
  success: boolean;
  error?: string;
  task?: {
    id: string;
    status: TaskStatus;
    extract_data?: string;
    metrics_tokens: number;
    metrics_time: number;
  };
}

/**
 * WorkflowApis interface - methods generated from your API dependencies
 */
export interface WorkflowApis {
  export_goods: (start_time: string, end_time: string) => Promise<ExecutionResult>;
  get_report_list: () => Promise<ExecutionResult>;
}


/**
 * Creates API client using agent.call()
 */
export function createWorkflowApis(agent: Agent): WorkflowApis {
  return {
  /**
   * Export goods
   * 打开商品库页面，在创建时间输入框中填入开始日期和结束日期，商品来源选择全部，然后点击导出按钮
   * @endpoint /v1/custom/https-store-youzan-com-export-goods-gf9oj9
   */
  async export_goods(start_time: string, end_time: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/https-store-youzan-com-export-goods-gf9oj9', {
      method: 'POST',
      body: { start_time, end_time },
    });
    return data;
  },

  /**
   * Get report list
   * 获取导出文件列表，获取导出文件列表，获取导出文件列表
   * @endpoint /v1/custom/https-store-youzan-com-get-report-list-38unjm
   */
  async get_report_list(): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/https-store-youzan-com-get-report-list-38unjm', {
      method: 'POST',
    });
    return data;
  },
  };
}
